### ISSUE TITLE
If a commit has known comments, display their count and link to them.

### ISSUE THREAD

**Issue by shurcooL** [shurcooL/Go-Package-Store#29]
Original inspiration is over at https://github.com/shurcooL/Go-Package-Store/commit/f93175e41607f67ba2ded91095bb26fd98ab285e#commitcomment-9233851.

The idea is to add a little unobtrusive comments counter with a link that takes you to comments. Primarily implementation is for GitHub, but in theory it's a general change that other presenters can support too.

![image](https://cloud.githubusercontent.com/assets/1924134/5697560/39e0c6dc-99a9-11e4-9faf-ef9aee4e7424.png)

In the screenshot above, it would link you directly to the comments on that commit:

https://github.com/gopherjs/gopherjs/commit/635a153b2f382fb394a1975f8196b6ca40477950#comments

**Comment by shurcooL** [comment]
By the way, thanks to @slimsag and @rebyn for inspiring this feature. :D

**Comment by rebyn** [comment]
Side note: I'm browsing the web interface from quite a big screen, which makes reading commit messages on the left then navigating to its link on the right a bit tough. How do you think about layouting commit link next to the message? Something like:

[SHA](Clickable) - Commit Message

**Comment by shurcooL** [comment]
> Side note: I'm browsing the web interface from quite a big screen, which makes reading commit messages on the left then navigating to its link on the right a bit tough. How do you think about layouting commit link next to the message? Something like:
> 
> [SHA](Clickable) - Commit Message

I think a better solution would be to cap the max-width of the content to something reasonably sane. Right now there is no cap, which I can imagine would make the changes and commit links unreadable and inconvenient.

I don't think putting the commit links on the right side is a good idea, because that information is secondary to the main content: the change message. I want to have more important information on the left, and less important details (if you're interested) to the right.

**Comment by rebyn** [comment]
> I don't think putting the commit links on the right side is a good idea, because that information is secondary to the main content: the change message. I want to have more important information on the left, and less important details (if you're interested) to the right.

UX wise, how about making commit message clickable (link it to GH link)?

**Comment by shurcooL** [comment]
That might work, I'll give it a try.
