### ISSUE TITLE
go get throws an error for 'https://azul3d.org/semver.v2/'

### ISSUE THREAD

**Issue by adityashedge** [shurcooL/Go-Package-Store#35]
Getting this on my 'Ubuntu 14.04.2 LTS'

$go get -u github.com/shurcooL/Go-Package-Store

Cloning into '~/golang/packages/src/azul3d.org/semver.v2'...
fatal: unable to access 'https://azul3d.org/semver.v2/': Failed to connect to azul3d.org port 443: Network is unreachable
package github.com/shurcooL/Go-Package-Store
	imports azul3d.org/semver.v2: exit status 128

Some help here please. Thank you in advance.

**Comment by slimsag** [comment]
Sorry to hear you're having trouble. Answers to these questions might help us identify the problem:

- Have you tried again after a few hours? (Perhaps a critical network path to the Seattle-based server went down temporarily, etc).
- Is the machine behind a firewall or proxy of some sort, and if so can you try with it disabled?
- Can you `curl` azul3d.org on that machine or another machine on the same network?
  - `curl https://azul3d.org`
  - `curl http://azul3d.org`
- Can you `ping` azul3d.org or it's IPV4 address ?
  - `ping azul3d.org`
  - `ping 107.191.116.242`
- What does `git ls-remote https://azul3d.org/semver.v2` report?
- Does `git clone -v https://azul3d.org/semver.v2` properly clone the repo on your machine?

Note: I'm not the author of G-P-S, but I run azul3d.org so I'll try to assist however I can. I just tried on Ubuntu 14.10 and it works totally fine on my network.

**Comment by adityashedge** [comment]
@slimsag ping works perfectly fine but everything else you suggested fails with same error message
"fatal: unable to access 'https://azul3d.org/semver.v2/': Failed to connect to azul3d.org port 443: Network is unreachable"

I have been trying for the past 2 hours and no luck yet. No firewall or proxy enabled.

**Comment by slimsag** [comment]
What's your public IP address? Looking at the server's logs I wonder if these are related:

```
2015/03/14 14:22:54 http: TLS handshake error from 217.197.4.130:54155: remote error: bad certificate
2015/03/14 14:26:11 http: TLS handshake error from 217.197.4.130:54563: remote error: bad certificate
2015/03/14 14:26:17 http: TLS handshake error from 217.197.4.130:54580: remote error: bad certificate
2015/03/14 14:26:23 http: TLS handshake error from 217.197.4.130:54597: remote error: bad certificate
2015/03/14 14:26:28 http: TLS handshake error from 217.197.4.130:54613: remote error: bad certificate
2015/03/14 14:26:34 http: TLS handshake error from 217.197.4.130:54630: remote error: bad certificate
2015/03/14 14:26:40 http: TLS handshake error from 217.197.4.130:54647: remote error: bad certificate
2015/03/14 14:26:45 http: TLS handshake error from 217.197.4.130:54660: remote error: bad certificate
2015/03/14 14:26:50 http: TLS handshake error from 217.197.4.130:54677: remote error: bad certificate
```

I'm not sure what's going on here. :/

**Comment by adityashedge** [comment]
that's not my IP but I can access the site and ping to it just fine.

**Comment by shurcooL** [comment]
Thanks for looking into this @slimsag.

Unfortunately, I cannot reproduce the issue either (just tried on a fresh Ubuntu 14.04 VM). It seems related to your configuration and the `https` protocol in some way.

**Comment by shurcooL** [comment]
Two more questions for you @adityashedge, can you please post what these two commands print on your machine:

```
go version
```

```
git version
```

That may be helpful.

**Comment by adityashedge** [comment]
@shurcooL 
go version go1.4.2 linux/amd64
git version 1.9.1

Also I tried with a different network and I am getting a different error now.
fatal: unable to access 'https://azul3d.org/semver.v2/': gnutls_handshake() failed: A TLS packet with unexpected length was received.

**Comment by slimsag** [comment]
@adityashedge I have a theory that it was a bug fixed after Go v1.3.1 (which the azul3d.org server was running). azul3d.org is now running Go v1.4.2 -- please try again.

If the issue is not resolved after that, I'll try disabling cloudflare on the site (which uses some newer HTTPS features that older gnutls version might be having trouble with).

**Comment by adityashedge** [comment]
@slimsag sry no luck still getting the same error in both scenarios.

**Comment by shurcooL** [comment]
Is this still an issue? I haven't been able to reproduce it in any scenario.

**Comment by adityashedge** [comment]
@shurcooL This is fixed. No idea how but it worked.

**Comment by shurcooL** [comment]
Glad to hear!
