### ISSUE TITLE
go get -u throws errors on codegoogle.go

### ISSUE THREAD

**Issue by sescobb27** [shurcooL/Go-Package-Store#37]
```
go get -u github.com/shurcooL/Go-Package-Store
# github.com/shurcooL/Go-Package-Store/presenter
github.com/shurcooL/Go-Package-Store/presenter/codegoogle.go:113: too many arguments in call to sg.Repository
github.com/shurcooL/Go-Package-Store/presenter/codegoogle.go:121: cannot use "sourcegraph.com/sourcegraph/go-vcs/vcs".RemoteOpts literal (type "sourcegraph.com/sourcegraph/go-vcs/vcs".RemoteOpts) as type *vcsclient.CloneInfo in argument to r.(vcsclient.RepositoryCloneUpdater).CloneOrUpdate
```
go version go1.4.2 linux/amd64

**Comment by shurcooL** [comment]
Hi @sescobb27,

Thanks for reporting this issue. I need to update the code because upstream API has changed slightly.

I will have a fix shortly, and it should work okay after that.

**Comment by shurcooL** [comment]
@sescobb27, this should be fixed now.

Can you please try `go get -u github.com/shurcooL/Go-Package-Store` again and let me know if everything's okay? Thanks again for reporting the issue!

**Comment by sescobb27** [comment]
:smiley: that was fast thank you so much, is working now
