### ISSUE TITLE
Error while installing on Windows 7

### ISSUE THREAD

**Issue by IndianGuru** [shurcooL/Go-Package-Store#46]
G:\go_projects\go>go get -u github.com/shurcooL/Go-Package-Store
# cd .; git clone https://azul3d.org/semver.v2 G:\go_projects\go\src\azul3d.org\
semver.v2
Cloning into 'G:\go_projects\go\src\azul3d.org\semver.v2'...
fatal: unable to access 'https://azul3d.org/semver.v2/': error:14077410:SSL rout
ines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
package azul3d.org/semver.v2: exit status 128

**Comment by shurcooL** [comment]
Hi there,

Thanks for reporting the issue. It's a known issue in a dependency which will be resolved upstream soon. See https://github.com/azul3d/semver/issues/15 for context.

> it will be inherently fixed once azul3d/website#11 is finished (hopefully by/before this weekend).

I will temporarily disable the azul3d presenter until it is resolved upstream. That will allow you to use Go Package Store today.

**Comment by shurcooL** [comment]
@IndianGuru, please try `go get -u github.com/shurcooL/Go-Package-Store` again and let me know if the issue is resolved for you.
