### ISSUE TITLE
Remove unnecessary analytics

### ISSUE THREAD

**Issue by jaredharley** [shurcooL/Go-Package-Store#48]
`main.go`, lines 39-51: Remove unnecessary Google Analytics tracking.

**Comment by shurcooL** [comment]
Why do you think they're unnecessary? I use them to have an idea of how many people are using the app, and that allows me to know how much of my time/resources I should put into making it better, etc.

See https://github.com/shurcooL/Go-Package-Store/commit/e294f927573ab24be168ea7733997bae61900dc9 for original rationale to add it.

**Comment by shurcooL** [comment]
Closing because it's not an issue as far as I can tell. Please re-open otherwise.
