### ISSUE TITLE
Feature Request: "Update All" button.

### ISSUE THREAD

**Issue by shurcooL** [shurcooL/Go-Package-Store#6]

**Comment by cnbuff410** [comment]
+1

**Comment by wienczny** [comment]
+1

**Comment by NHOrus** [comment]
+1

**Comment by shurcooL** [comment]
> The harder part is updating the UI to reflect which packages have been updated (it should be all of them... but finding out when each individual package is updated is tricky).

Good news (after 2 years). As I'm making progress on completing #67, I'm realizing that implementing this feature will finally become very viable. Soon now!

**Comment by shurcooL** [comment]
Here's a 10-second video preview of the work in progress.

[![](https://cloud.githubusercontent.com/assets/1924134/23282827/0b2faf4c-f9f1-11e6-867e-7b973b7212e9.png)](http://instantshare.virtivia.com:27080/1hux0d5kqpoj2.mov)
