### ISSUE TITLE
Don't use a popup if the program is stopped

### ISSUE THREAD

**Issue by mvdan** [shurcooL/Go-Package-Store#66]
I would say a big red warning at the top of the web page would be better. Perhaps disabling all the buttons too, since they would not do anything.

A popup bothers me because it makes my browser jump and I lose what tab I was in. I understand that this tab is now dead and should be closed, but I don't see the urgency and need to do a popup.

**Comment by shurcooL** [comment]
Agreed.

I've wanted this too (not that strongly, but a bit). It's just a matter of doing it.

This will be easier to do once/if the frontend is made more dynamic (i.e., once there are multiple tabs and the ability to seamlessly switch between them), but it can be done anytime.

**Comment by shurcooL** [comment]
I'm going to resolve this issue in the next release by simply removing the current feature. The current implementation is half-baked, and below the usability standard.

After it's removed, I can consider adding a higher quality version of the notification that the backend is disconnected (without the popup).

**Comment by mvdan** [comment]
@shurcooL thanks for the update - sounds like a good idea.
