### ISSUE TITLE
HEAD branch not found in ls-remote output

### ISSUE THREAD

**Issue by bits01** [shurcooL/Go-Package-Store#79]
See attached [vendor.json](https://github.com/shurcooL/Go-Package-Store/files/948428/vendor.txt) file (using `govendor` for vendoring).

```
% Go-Package-Store -govendor vendor/vendor.json
Reading the list of Go packages from vendor.json file: vendor/vendor.json
Go Package Store server is running at http://localhost:7043/updates.
skipping "cloud.google.com/go" because of remote error:
	HEAD branch not found in ls-remote output
skipping "google.golang.org/api" because of remote error:
	HEAD branch not found in ls-remote output
```

**Comment by shurcooL** [comment]
Thanks, I can reproduce. Will investigate.

**Comment by shurcooL** [comment]
Yeah, this is definitely fixable on my part. Thanks for the bug report.

**Comment by bits01** [comment]
Thanks, look forward to the fix. Very useful tool to get a sense of any available updates for vendored packages and a list of changes.

**Comment by shurcooL** [comment]
This has been fixed via https://github.com/shurcooL/vcsstate/commit/0087ee72f10e9197a573c237b0a41faface2b648.

If you @bits01 install latest Go Package Store (the usual way, `go get -u github.com/shurcooL/Go-Package-Store/cmd/Go-Package-Store`), you should not get those errors anymore.

Let me know if anything else comes up.

**Comment by bits01** [comment]
Thank you! It works.
