### ISSUE TITLE
Is this still an active project? What can we use with go modules?

### ISSUE THREAD

**Issue by frederikhors** [shurcooL/Go-Package-Store#96]
Is this still an active project?

What can we use with go modules?

**Comment by dmitshur** [comment]
Yes, I use Go Package Store weekly and actively maintain it.

Adding support for Go modules is issue #92. I plan to do it. I suggest you add a :+1: reaction there and subscribe to the issue for further updates.

**Comment by frederikhors** [comment]
Is this just a web page or maybe can I use it also in console?

**Comment by dmitshur** [comment]
Go Package Store a web app only. It uses a browser to display the available updates using HTML.
